endpoint: https://unbounce.atlassian.net
user: alex.kononovich@unbounce.com
password-source: keyring
custom-commands:
  - name: overview
    help: Show tickets in different columns
    script: |-
      echo 'Test:'
      {{jira}} list-test
      echo '\nReview:'
      {{jira}} list-review
      echo '\nIn Progress:'
      {{jira}} list-in-progress
      echo '\nTodo:'
      {{jira}} list-todo
      echo '\nDeploy:'
      {{jira}} list-deploy
  - name: assign-current
    help: Assign ticket for current branch
    args:
      - name: ASSIGNEE
        required: true
    script: |-
      current-jira-ticket | xargs -I{} {{jira}} assign {} {{args.ASSIGNEE}}
  - name: view-current
    help: View ticket for current branch
    script: |-
      current-jira-ticket | xargs {{jira}} view
  - name: view-mine
    help: Display issues assigned to me and then pick one to view
    script: |-
      {{jira}} list-mine | fzf | awk -F ':' '{print $1}' | xargs {{jira}} view
  - name: browse-current
    help: Open ticket for current branch in browser
    script: |-
      current-jira-ticket | xargs {{jira}} browse
  - name: list-mine
    help: Display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"
  - name: list-review
    help: Display issues in Review column
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status=Review ORDER BY created"
  - name: list-test
    help: Display issues in Test column
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status=Test ORDER BY created"
  - name: list-in-progress
    help: Display issues in In Progress column
    script: |-
      {{jira}} list --query "resolution=unresolved and issuetype not in ('Epic') and project=PL and status='In Progress' ORDER BY created"
  - name: list-todo
    help: Display issues in Todo column
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status in ('Open', 'Backlog') and sprint in openSprints () ORDER BY created"
  - name: list-deploy
    help: Display issues in Deploy column
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status=Deploy ORDER BY created"
  - name: what-to-review
    help: Display issues in Review column that are unassigned
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status=Review and assignee=null ORDER BY created"
  - name: what-to-test
    help: Display issues in Test column that are unassigned
    script: |-
      {{jira}} list --query "resolution=unresolved and project=PL and status=Test and assignee=null ORDER BY created"
  - name: edit-mine
    help: Display issues assigned to me and then pick one to edit
    script: |-
      {{jira}} list-mine | fzf | awk -F ':' '{print $1}' | xargs {{jira}} edit
  - name: transition-current
    help: Move current ticket to another state
    script: |-
      current-jira-ticket | xargs {{jira}} transition-and-unassign
  - name: transition-mine
    help: Display issues assigned to me and then pick one to transition to another state
    script: |-
      {{jira}} list-mine | fzf --sync | awk -F ': ' '{print $1}' | xargs {{jira}} transition-and-unassign
  - name: transition-and-unassign
    help: Transition ticket to a new state and unassign
    args:
      - name: ISSUE
        required: true
    script: |-
      new_state=$(jira transitions {{args.ISSUE}}| fzf --sync | awk -F ': ' '{print $2}')
      if [[ ! -z $new_state ]]; then
        {{jira}} transition "${new_state}" {{args.ISSUE}}
        {{jira}} unassign {{args.ISSUE}}
      fi
  - name: start-ticket
    help: Start working on a ticket
    args:
      - name: ISSUE
        required: true
    script: |-
      jira take {{args.ISSUE}} alex.kononovich
      jira transition --noedit 'In Progress' {{args.ISSUE}}
      git checkout -b {{args.ISSUE}}
      jira view {{args.ISSUE}}
  - name: finish-ticket
    help: Finish ticket, create a PR and put it into Review
    script: |-
      git push origin head
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      PR_URL=$(hub pull-request)
      ISSUE=$(current-jira-ticket)
      {{jira}} edit -o customfield_10043="${PR_URL}" -o customfield_10051="${CURRENT_BRANCH}" --noedit $ISSUE
      {{jira}} transition --noedit 'Review' $ISSUE
      {{jira}} unassign $ISSUE
      hub browse-current
      jira browse-current
      git checkout master
