#!/bin/sh
set -e
git_dir="`git rev-parse --git-dir`"
temp_tags_file="$git_dir/$$.tags"
working_dir=$(pwd)
trap 'rm -f "$temp_tags_file"' EXIT

# Ctags for usual stuff and *.elm files for libraries
{ if [[ -d elm-stuff/packages ]]; then find elm-stuff/packages -type f -name "*.elm"; fi; git ls-files; } | \
  ctags --tag-relative -L - -f"$temp_tags_file" --languages=-sql

# Haskell tags (based on http://www.atn34.com/posts/git-hooks-and-haskell-tags.html)
if [[ -x "$(command -v hasktags)" ]] && [[ -f "$working_dir/stack.yaml" ]]; then
  hasktags -c -x --ignore-close-implementation -a -f "$temp_tags_file" "$working_dir"
  LC_COLLATE=C sort "$temp_tags_file" -o "$temp_tags_file"
fi

mv "$temp_tags_file" "$git_dir/tags"
