#!/bin/sh
set -e
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
{ if [[ -d elm-stuff/packages ]]; then find elm-stuff/packages -type f -name "*.elm"; fi; git ls-files; } | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-sql
mv "$dir/$$.tags" "$dir/tags"
